"""What one dig step costs: march one cell + fight the cell's defenders.

A cell's defenders are generated by the engine from ``(landId, attrLv)`` where
``attrLv = clamp(dist_to_main, 1, n[land lv])`` (``getLandAttrLvByDis``), so one
sim per distinct pair covers a whole plan. The dig group is assumed healthy
(HealRouting + Cứ Điểm restore it between steps). A battle the group can't win
within ``max_loss`` makes the cell *hard* (``None``).
"""
from __future__ import annotations

import logging
import math
from collections.abc import Callable

log = logging.getLogger(__name__)

# engine getLandAttrLvByDis: cap of the distance level per land lv (default 10)
_ATTR_CAP = {1: 12, 2: 12, 3: 12, 4: 15, 5: 16}
# battle length when the sim can't say (rough, by land level)
ROUGH_BATTLE_S = {0: 30.0, 1: 20.0, 2: 30.0, 3: 45.0, 4: 60.0, 5: 90.0}
DEFAULT_SPEED = 62  # slowest common pawn march_speed (~58 s per cell)


def march_ms(dist: float, speed: float, cd_pct: float = 0.0) -> int:
    """Engine getMarchTime: ``floor(dis * 3_600_000 / marchSpeed) * (1 - cd%)``."""
    speed = speed if speed and speed > 0 else DEFAULT_SPEED
    return int(math.floor(dist * 3_600_000 / speed) * (1 - cd_pct / 100))


def attr_lv(dist: int, land_lv: int) -> int:
    return max(1, min(int(dist), _ATTR_CAP.get(int(land_lv), 10)))


class CellCost:
    """``cost(idx)`` -> seconds for the dig group to take ``idx``, or ``None`` (hard).

    ``predict(idx, land_id, dist) -> BattlePrediction`` runs the sim (raises when
    it can't); ``dist_fn(idx)`` = Manhattan distance to the main-city block.
    """

    def __init__(self, predict: Callable, world, *, dist_fn: Callable[[int], int],
                 max_loss: float, speed: float):
        self.predict = predict
        self.world = world
        self.dist_fn = dist_fn
        self.max_loss = float(max_loss or 0)
        self.step_march_s = march_ms(1, speed) / 1000
        self.memo: dict[tuple[int, int], float | None] = {}
        self.loss: dict[tuple[int, int], float | None] = {}  # hard: predicted loss%, None = a defeat
        self.rough = False   # some cell was estimated without the sim
        self.sims = 0

    def battle_s(self, idx: int) -> float | None:
        land_id = self.world.land_id(idx)
        lv = self.world.lv(idx)
        dist = self.dist_fn(idx)
        key = (land_id, attr_lv(dist, lv))
        if key not in self.memo:
            try:
                self.sims += 1
                pred = self.predict(idx, land_id, dist)
            except Exception as e:  # sim down/crash: estimate, don't block the plan
                log.debug("dig cost sim failed for %s: %s", idx, e)
                self.rough = True
                self.memo[key] = ROUGH_BATTLE_S.get(lv, 60.0)
            else:
                if not pred.win or pred.loss_percent > self.max_loss:
                    self.memo[key] = None
                    self.loss[key] = float(pred.loss_percent) if pred.win else None
                elif pred.duration_s is None:
                    self.rough = True
                    self.memo[key] = ROUGH_BATTLE_S.get(lv, 60.0)
                else:
                    self.memo[key] = float(pred.duration_s)
        return self.memo[key]

    def hard_loss(self, idx: int) -> float | None:
        """For a hard cell: the loss % the win would cost (None = the group loses)."""
        lv = self.world.lv(idx)
        return self.loss.get((self.world.land_id(idx), attr_lv(self.dist_fn(idx), lv)))

    def cost(self, idx: int) -> float | None:
        b = self.battle_s(idx)
        return None if b is None else self.step_march_s + b
