"""What one dig step costs: march one cell + fight the cell's defenders.

A cell's defenders are generated by the engine from ``(landId, attrLv)`` where
``attrLv = clamp(dist_to_main, 1, n[land lv])`` (``getLandAttrLvByDis``), so one
sim per distinct pair covers a whole plan. The dig group is assumed healthy
(HealRouting + Cứ Điểm restore it between steps). A battle the group can't win
within ``max_loss`` makes the cell *hard* (``None``).
"""
from __future__ import annotations

import logging
import math
from collections.abc import Callable

log = logging.getLogger(__name__)

# engine getLandAttrLvByDis: cap of the distance level per land lv (default 10)
_ATTR_CAP = {1: 12, 2: 12, 3: 12, 4: 15, 5: 16}
# battle length when the sim can't say (rough, by land level)
ROUGH_BATTLE_S = {0: 30.0, 1: 20.0, 2: 30.0, 3: 45.0, 4: 60.0, 5: 90.0}
DEFAULT_SPEED = 62  # slowest common pawn march_speed (~58 s per cell)


def march_ms(dist: float, speed: float, cd_pct: float = 0.0) -> int:
    """Engine getMarchTime: ``floor(dis * 3_600_000 / marchSpeed) * (1 - cd%)``."""
    speed = speed if speed and speed > 0 else DEFAULT_SPEED
    return int(math.floor(dist * 3_600_000 / speed) * (1 - cd_pct / 100))


def attr_lv(dist: int, land_lv: int) -> int:
    return max(1, min(int(dist), _ATTR_CAP.get(int(land_lv), 10)))


class CellCost:
    """``cost(idx)`` -> seconds for the dig group to take ``idx``, or ``None`` (hard).

    ``predict(idx, land_id, dist) -> BattlePrediction`` runs the sim on the
    engine-GENERATED defenders (raises when it can't); ``dist_fn(idx)`` =
    Manhattan distance to the main-city block. The generator gives monsters
    RANDOM gear (``Math.random`` in getAreaPawnConfInfo), so a (landId, attrLv)
    verdict is only a screen: a cell it calls hard is re-checked with
    ``verify(idx)`` (the cell's REAL defenders from get_area -> BattlePrediction,
    or None when unknown), memoised per cell.
    """

    def __init__(self, predict: Callable, world, *, dist_fn: Callable[[int], int],
                 max_loss: float, speed: float, verify: Callable | None = None):
        self.predict = predict
        self.verify = verify
        self.world = world
        self.dist_fn = dist_fn
        self.max_loss = float(max_loss or 0)
        self.step_march_s = march_ms(1, speed) / 1000
        self.memo: dict[tuple[int, int], float | None] = {}
        self.loss: dict[tuple[int, int], float | None] = {}  # hard: predicted loss%, None = a defeat
        self.cell: dict[int, float | None] = {}       # per-cell verdict (real defenders)
        self.cell_loss: dict[int, float | None] = {}
        self.rough = False   # some cell was estimated without the sim
        self.sims = 0
        self.verified = 0

    def _key(self, idx: int) -> tuple[int, int]:
        return (self.world.land_id(idx), attr_lv(self.dist_fn(idx), self.world.lv(idx)))

    def _judge(self, pred, lv: int) -> tuple[float | None, float | None]:
        """(battle seconds or None if hard, loss% of a hard win / None)."""
        if not pred.win or pred.loss_percent > self.max_loss:
            return None, (float(pred.loss_percent) if pred.win else None)
        if pred.duration_s is None:
            self.rough = True
            return ROUGH_BATTLE_S.get(lv, 60.0), None
        return float(pred.duration_s), None

    def battle_s(self, idx: int) -> float | None:
        if idx in self.cell:
            return self.cell[idx]
        land_id = self.world.land_id(idx)
        lv = self.world.lv(idx)
        dist = self.dist_fn(idx)
        key = self._key(idx)
        if key not in self.memo:
            try:
                self.sims += 1
                pred = self.predict(idx, land_id, dist)
            except Exception as e:  # sim down/crash: estimate, don't block the plan
                log.debug("dig cost sim failed for %s: %s", idx, e)
                self.rough = True
                self.memo[key] = ROUGH_BATTLE_S.get(lv, 60.0)
            else:
                self.memo[key], self.loss[key] = self._judge(pred, lv)
        if self.memo[key] is not None or self.verify is None:
            return self.memo[key]
        # screened hard: settle it on this cell's real defenders
        try:
            real = self.verify(idx)
        except Exception as e:  # a probe failure keeps the screen's verdict
            log.debug("dig cost verify failed for %s: %s", idx, e)
            real = None
        if real is None:
            self.cell[idx], self.cell_loss[idx] = None, self.loss.get(key)
        else:
            self.verified += 1
            self.cell[idx], self.cell_loss[idx] = self._judge(real, lv)
        return self.cell[idx]

    def hard_loss(self, idx: int) -> float | None:
        """For a hard cell: the loss % the win would cost (None = the group loses)."""
        if idx in self.cell_loss:
            return self.cell_loss[idx]
        return self.loss.get(self._key(idx))

    def cost(self, idx: int) -> float | None:
        b = self.battle_s(idx)
        return None if b is None else self.step_march_s + b
